export const Images = {
  logo: require("./logo.svg"),
  aliens: require("./aliens.png"),
  mage: require("./mage.png"),
  darkswordman: require("./dark-swordsman.png"),
  mouse: require("./mouse.png"),
  keyboard: require("./keyboard.png"),
  headset: require("./headphone.png"),
  megaphone: require("./megaphone.png"),
  confetti: require("./confetti.png"),
  lines01: require("./line.png"),
  lines02: require("./line02.png"),
  render3d: require("./3d_render.png"),
  render3d_01: require("./3d_render01.png"),
  glow: require("./glow.png"),
  smoke01: require("./smoke01_1.png"),
  smoke02: require("./smoke01_2.png"),
  smoke1_01: require("./smoke_1.png"),
  smoke1_02: require("./smoke_2.png"),
  logo01: require("./logo01.png"),
  logo02: require("./logo.png"),
  sparks: require("./sparks.png"),
  sparks01: require("./sparks01.png"),
  crown: require("./crown.png"),
  trophy: require("./trophy.png"),
  background: require("./bg_image.png"),
  chevron_left: require("./chevron-left.svg"),
  chevron_right: require("./chevron-right.svg"),
  menu: require("./menu.svg"),
  partners: {
    partner01: require("./partners/image_78.png"),
    partner02: require("./partners/image_79.png"),
    partner03: require("./partners/image_80.png"),
    partner04: require("./partners/image_81.png"),
    partner05: require("./partners/image_82.png"),
    partner06: require("./partners/image_83.png"),
    partner07: require("./partners/image_84.png"),
  },
  socials: {
    twitter: require("./socials/twitter.svg"),
    discord: require("./socials/discord.svg"),
    twitch: require("./socials/twitch.svg"),
  },
  team: {
    member01: require("./team/Rectangle_88.png"),
  },
  players: {
    member01: require("./players/Rectangle_289.png"),
  },
  arrowRight: require("./arrow-right.svg"),
};
